version: "3.3"
services:
  web-app:
    container_name: "debug_coppo_api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8070:80"
    networks:
      default:
        ipv4_address:  172.18.0.8
    restart: always

networks:
  default:
    external:
      name: docker-network